"""Table counter

Revision ID: 96edb3d420c5
Revises: 6bf60b79ff33
Create Date: 2022-11-28 15:27:43.567244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96edb3d420c5'
down_revision = '6bf60b79ff33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tablecounter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('client_info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tablecounter_id'), 'tablecounter', ['id'], unique=False)
    op.drop_index('ix_Table counter_id', table_name='Table counter')
    op.drop_table('Table counter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Table counter',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Table counter_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('client_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Table counter_pkey')
    )
    op.create_index('ix_Table counter_id', 'Table counter', ['id'], unique=False)
    op.drop_index(op.f('ix_tablecounter_id'), table_name='tablecounter')
    op.drop_table('tablecounter')
    # ### end Alembic commands ###
